---
title: "Tutorials"
output:
  html_document:
    fig_caption: yes
    theme: cerulean
    toc: yes
    toc_depth: 3
    toc_float: yes
---

[benjburgess.github.io](https://benjburgess.github.io/)

Outlined below are all the tutorials currently written on various different topics.

Note that these will continue to be added over the coming weeks.

## Statistics, Data Modelling, and Machine Learning

### Meta-analyses
An [introductory tutorial for meta-analyses](https://benjburgess.github.io/i/metaanalysis_introductory) where `R` code is provided. The tutorial provides a step-by-step workflow for how to conduct a meta-analysis including addressing issues with covariance, hierarchical random effects, and fixed effects.


### Support Vector Machines (SVMs)

An [introductory tutorial for SVMs](https://benjburgess.github.io/i/SVM_linear) where `R` code is provided. The tutorial builds a simple SVM which accurately which can accurately classify two species based on physical measurements.

An [advanced tutorial for SVMs](https://benjburgess.github.io/i/SVM_radial) where `R` code is provided. The tutorial utilises on an openly available dataset on wine. This example generates a SVM which attempts to classifies wines into different qualities, based on the chemical properties of the wine. 


## multiplestressR - R package

### Introductory tutorial

The [introductory tutorial](https://benjburgess.github.io/i/multiplestressR1) covers the basics of the `multiplestressR` package. Alongside the installation of this package, an example step-by-step work through is also provided. 



## Links

[benjburgess.github.io](https://benjburgess.github.io/)